### ISSUE TITLE
Inventory blacklist not working in `jade_plugins.json`

### ISSUE THREAD

**Issue by Adam-Kay** [Snownee/Jade#369]
### Mod loader

Fabric

### Minecraft version

1.18.2

### Mod version

Jade-1.18.2-forge-5.3.1.jar

### Modloader version

Forge 40.2.4

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/XKZin7Zn

### Issue description

The blacklist section of ~~`jade_plugins.json`~~ `jade_addons.toml` does not appear to work for excluding certain inventories. 

I was trying to remove a modded inventory block from showing its contents in Jade, and noticed that adding the ID to the blacklist didn't seem to do anything in Jade. I tested it using a vanilla block (in this case the minecraft chest), and it still doesn't do anything. 

I also changed the `normalShowAmount` to test that the config was being loaded correctly, and it was (can see in the screenshots, the show amount was limited to 5).

<details><summary><h3><s><code>jade_plugins.json</code></s> <code>jade_addons.toml</code> configuration</h3> <i>[click to show]</i></summary>

```toml

[inventory]
	#Range: 0 ~ 54
	sneakShowAmount = 54
	#Range: 0 ~ 54
	normalShowAmount = 5
	#Range: 1 ~ 18
	showItemPreLine = 9
	blacklist = ["minecraft:chest"]
	bypassLockedContainer = false

[customContainerName]
	onlyShowVanilla = false
	blacklist = ["thermal"]

```
</details> 

### Screenshots:
![2024-02-03_16-50-37_notepad++_NJ6](https://github.com/Snownee/Jade/assets/10010491/c17dd91f-6f5d-46b3-8787-972a60b2f139)
![2024-02-03_16-50-47_javaw_VSX](https://github.com/Snownee/Jade/assets/10010491/d193f3dc-01b1-418f-9e46-70b423f67268)

Am I configuring the TOML file wrong somehow, or does blacklist not work the way I thought it would? Or is it just a bug in this version? I have the latest version of Jade for 18.2 .
